# -> define theme
palette = "catppuccin_mocha"

# -> definiciones principales
[directory]
truncation_length = 5
format = "[$path]($style)[$lock_symbol]($lock_style) "

[battery]
full_symbol = "ó°¹ "
charging_symbol = "ó°‚„ "
discharging_symbol = "ó±‰ž "

[[battery.display]]
threshold = 30
style = "bold red"

[username]
show_always = true
style_user = "bold red"
format = '[@$user ]($style)'

[hostname]
ssh_only = false
format = "[$hostname](bold flamingo) "
style = "bold flamingo"

[character]
success_symbol = "[ï² ](bold red)"
error_symbol = "[âœ— ](bold red)"

[cmd_duration]
style = "bold peach"

[git_branch]
style = "bold mauve"

[git_status]
conflicted = "ï™ "
ahead = "ï‘¿ "
behind = " ó±Š¾ "
diverged = "ó±¡· "
untracked = "ï„¨"
stashed = "ï‘³ "
modified = "ï€ "
staged = "ï® "
renamed = "î­¾ "
deleted = "ó°†´ "
style = "bold blue"

[time]
time_format = "%"
format = "ðŸ•™ $time($style) "
style = "bold sapphire"
disabled = true

[julia]
format = "[$symbol$version]($style) "
symbol = "à®ƒ "
style = "bold green"

[memory_usage]
format = "$symbol[${ram}( | ${swap})]($style) "
threshold = 70
style = "bold dimmed white"
disabled = false

[package]
disabled = true

[python]
format = "[$symbol$version]($style) "
symbol = "ó°Œ  "
style = "bold green"

[rust]
format = "[$symbol$version]($style) "
symbol = "îž¨ "
style = "bold green"

[nodejs]
format = "via [ó°Ž™ $version](bold green) "

# -> include theme mocha
[palettes.catppuccin_frappe]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#FF3030"